### ISSUE TITLE
Crashing Initializing game

### ISSUE THREAD

**Issue by CreeperRobot8815** [skmedix/SKlauncher#154] opened 2019-06-16 10:33 UTC
Whenever I Run My Minecraft Then This Crash Report Pops Up:

Description: Initializing game

java.lang.IllegalStateException: GLFW error 65542: WGL: The driver does not appear to support OpenGL
	at cud.b(SourceFile:195)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1666)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1847)
	at cud.<init>(SourceFile:86)
	at dkz.a(SourceFile:36)
	at cvk.au(SourceFile:465)
	at cvk.b(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:154)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
        at cud.b(SourceFile:195)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1666)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1847)
	at cud.<init>(SourceFile:86)
	at dkz.a(SourceFile:36)
	at cvk.au(SourceFile:465)

-- Initialization --
Details:
Stacktrace:
        at cvk.b(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:154)

-- System Details --
Details:
        Minecraft Version: 1.14.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 361241912 bytes (344 MB) / 536870912 bytes (512 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: 1.14.2
	LWJGL: 3.2.1 build 12
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by skmedix** [comment] 2019-07-07 18:52
Duplicate of #136

**Closed by skmedix** 2019-07-07 18:52 UTC

**Comment by RadioactivePlays** [comment] 2019-07-10 09:41
> Whenever I Run My Minecraft Then This Crash Report Pops Up:
> 
> Description: Initializing game
> 
> java.lang.IllegalStateException: GLFW error 65542: WGL: The driver does not appear to support OpenGL
> at cud.b(SourceFile:195)
> at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
> at org.lwjgl.system.JNI.invokePPPP(Native Method)
> at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1666)
> at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1847)
> at cud.(SourceFile:86)
> at dkz.a(SourceFile:36)
> at cvk.au(SourceFile:465)
> at cvk.b(SourceFile:395)
> at net.minecraft.client.main.Main.main(SourceFile:154)
> 
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> -- Head --
> Thread: Client thread
> Stacktrace:
> at cud.b(SourceFile:195)
> at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
> at org.lwjgl.system.JNI.invokePPPP(Native Method)
> at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1666)
> at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1847)
> at cud.(SourceFile:86)
> at dkz.a(SourceFile:36)
> at cvk.au(SourceFile:465)
> 
> -- Initialization --
> Details:
> Stacktrace:
> at cvk.b(SourceFile:395)
> at net.minecraft.client.main.Main.main(SourceFile:154)
> 
> -- System Details --
> Details:
> Minecraft Version: 1.14.2
> Operating System: Windows 10 (amd64) version 10.0
> Java Version: 1.8.0_181, Oracle Corporation
> Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> Memory: 361241912 bytes (344 MB) / 536870912 bytes (512 MB) up to 2147483648 bytes (2048 MB)
> JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
> Launched Version: 1.14.2
> LWJGL: 3.2.1 build 12
> OpenGL: NO CONTEXT
> GL Caps:
> Using VBOs: Yes
> Is Modded: Probably not. Jar signature remains and client brand is untouched.
> Type: Client (map_client.txt)
> Resource Packs:
> Current Language: ~ERROR~ NullPointerException: null
> CPU:

Deve ser porque o seu driver de video não Suporta o OpenGL... tenta baixar a versão 7 do java pro seu sistema operacional(32 ou 64 bits), baixa esse arquivo https://mega.nz/#!9KYnkA4B!qJRohuHtY5pnmxo9h1HkBzNveVjIn2N7hT8wYKQLX88 , extrai e cola na pasta do seu Minecraft. pra mim funcionou
