### ISSUE TITLE
plz help sklauncher is not working

### ISSUE THREAD

**Issue by bonkxd1234** [skmedix/SKlauncher#379] opened 2021-01-06 01:37 UTC
i launch every time and not working any fix plz

**Comment by Indexerrowaty** [comment] 2021-01-06 01:47
Duplicate of #376 

There are 2 ways to fix this issue.
1. Download .jar (Universal) version of SKlauncher.
Or
2. Download and install Oracle Java 8. https://java.com/en/download/manual.jsp

**Closed by Indexerrowaty** 2021-01-06 01:47 UTC
