### ISSUE TITLE
Launcher stuck on "Loading" 

### ISSUE THREAD

**Issue by LewdAngel** [skmedix/SKlauncher#198] opened 2019-09-04 16:09 UTC
Completely randomly my launcher stopped working, when i open it usually it loads my profiles and i can click the 'Play (version)' button on the bottom left to start the game. This button however is now unclickable and just says 'Loading'. 
My launcher log stops at:
[17:55:23 INFO]: SKlauncher 3.0-3abcecd started on windows...
[17:55:23 INFO]: Current time is Sep 4, 2019 5:55:23 PM
[17:55:23 INFO]: System.getProperty('os.name') == 'Windows 10'
[17:55:23 INFO]: System.getProperty('os.version') == '10.0'
[17:55:23 INFO]: System.getProperty('os.arch') == 'amd64'
[17:55:23 INFO]: System.getProperty('java.version') == '1.8.0_221'
[17:55:23 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[17:55:23 INFO]: System.getProperty('sun.arch.data.model') == '64'
[17:55:23 INFO]: proxy == DIRECT
[17:55:23 INFO]: Refreshing local version list...
[17:55:23 INFO]: Refreshing remote version list...
[17:55:24 INFO]: Refresh complete.
[17:55:24 INFO]: Loaded 4 profile(s); selected 'LewdAngel'
[17:55:24 INFO]: Refreshing auth...
[17:55:24 INFO]: Logging in with username in offline mode

And after this nothing, it doesn't seem to want to load up and i can't start the game. I've tried disconnecting/reconnecting from the internet and relaunching the app or changing the profile and logging out - in, but nothing seems to work. 
Any help with this?

**Comment by Bleidd64** [comment] 2019-09-04 16:17
Duplicate of #197. A fix is expected to drop soon, but there is a workaround in issue I linked.

**Closed** 2019-09-04 17:19 UTC
